### ISSUE TITLE
Dependency problem added as a library

### ISSUE THREAD

**Issue by ceyhunsen** [Bitcoin-Wildlife-Sanctuary/bitcoin-simulator#1]
# Description

I use Bitcoin dependency in my project. And it is fetched directly from crates.io. I don't know if BitVM branched `rust-bitcoin` plays nicely with major release.

Although running unit tests won't throw any build errors, using this library as a dependency throws this build error:

```sh
error: failed to select a version for `base58check`.
    ... required by package `bitcoin v0.31.0 (https://github.com/rust-bitcoin/rust-bitcoin?branch=bitvm#48efda92)`
    ... which satisfies git dependency `bitcoin` of package `bitcoin-simulator v0.1.0 (https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-simulator.git#40c1d370)`
    ... which satisfies git dependency `bitcoin-simulator` of package `clementine-core v0.1.0 (/home/ceyhunsen/chainway/projects/clementine/core)`
versions that meet the requirements `^0.1.0` are: 0.1.0

the package `bitcoin` depends on `base58check`, with features: `std` but `base58check` does not have these features.


failed to select a version for `base58check` which could resolve this conflict
```

My library uses these related dependencies:

```toml
bitcoin = { version = "0.31.1", features = ["rand", "bitcoinconsensus"] }
bitcoincore-rpc = "0.18.0"
risc0-zkvm = { version = "0.21.0" }
```

Tried to use `bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin", branch = "bitvm", features = ["rand"] }` (dependency of this repo) instead of directly fetching a the version above from crates.io didn't help (same error).

This error might not be directly related to this library but related to BitVM branch of `rust-bitcoin` itself. Is this error known? Are there any recommendations for solving this?

**Comment by weikengchen** [comment]
The issue seems to mostly due to the necessity of patches. See Cargo.toml of this repo for reference.

**Comment by weikengchen** [comment]
This PR should have addressed the issue:
https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-simulator/commit/6f6b19ff6c154090dbd38b5124db0aca55b8310b
